package de.linkel.aoc

class Day08Test: AbstractDayTest<Long>() {
    override val exampleA = """
............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............
        """.trimIndent()
    override val exampleSolutionA = 14L
    override val solutionA = 313L


//    override val exampleB = """
//        """.trimIndent()
    override val exampleSolutionB = 34L
    override val solutionB = 1064L

    override val implementation = Day08()
}
